# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

safe: true
lsi: false

# Site settings
title: Try to writing anyway
email: geeksaga@geeksaga.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geeksaga.com" # the base hostname & protocol for your site
twitter_username: geeksaga 
github_username:  geeksaga 

# Build settings
markdown: kramdown

permalink: pretty
#highlighter: pygments
#
#gems:
#      - jemoji

#paginate: 10
